name: jumphost_implementation
on:
  workflow_dispatch:
    inputs:
      tag: 
        description: "Tag, e.g., SP.0.0.0"
        required: true
      OrgRepo:
        type: choice
        description: "org/repo, e.g., ncmsdev/ocpp-server"
        required: true
        options:
        - ncmsdev/ocpp-server
jobs:
  jumphost:
    runs-on: ubuntu-latest
    steps: 
    - name: 'Checkout Source-repo'
      uses: actions/checkout@main
      
    - name: Install Azure CLI 
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
    - name: Login to Azure
      run: |
        az login
        az account set --subscription 92795555-74c0-409e-bf60-edb488699fb3
        
    - name: jumphost login
      run: |
        az ssh vm --port 1224 --name numocity-jump-host --resource-group numocity-jump-host_group "git clone https://github.com/nischitha24/release_1.git"
        az ssh vm --port 1224 --name numocity-jump-host --resource-group numocity-jump-host_group "bash release_1/makeCompose.sh ${{ secrets.ORG_NPM_INSTALL }} ${{ inputs.OrgRepo }} ${{ inputs.tag }}"
    
    
