name: jumphost_implementation
on:
  workflow_dispatch:
    inputs:
      tag: 
        description: "Tag, e.g., SP.0.0.0"
        required: true
      OrgRepo:
        type: choice
        description: "org/repo, e.g., ncmsdev/ocpp-server"
        required: true
        options:
        - ncmsdev/ocpp-server
jobs:
  jumphost:
    runs-on: ubuntu-latest
    steps: 
    - name: 'Checkout Source-repo'
      uses: actions/checkout@main
    - name: Install Azure CLI 
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Login to Azure
      run: az login
    - name: Set the default subscription
      run: az account set --subscription 92795555-74c0-409e-bf60-edb488699fb3
    - name: jumphost login
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        mkdir -p ~/.ssh
        ssh-keyscan -p 1224 20.65.64.224 >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts
        bash test.sh ${{ secrets.ORG_NPM_INSTALL }} ${{ inputs.OrgRepo }} ${{ inputs.tag }}
