name: jumphost_implementation
on:
  workflow_dispatch:
    inputs:
      tag: 
        description: "Tag, e.g., SP.0.0.0"
        required: true
      OrgRepo:
        type: choice
        description: "org/repo, e.g., ncmsdev/ocpp-server"
        required: true
        options:
        - ncmsdev/ocpp-server
      Host:
        type: choice
        description: "choose the host to deploy services"
        required: true
        options:
        - cmsfusiontest.numocity.in
jobs:
  jumphost:
    runs-on: ubuntu-latest
    steps: 
    - name: 'Checkout Source-repo'
      uses: actions/checkout@main
      
    - name: Install Azure CLI 
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add --name ssh --version 1.1.3
        
    - name: Login to Azure
      run: |
        az login
        az account set --subscription 92795555-74c0-409e-bf60-edb488699fb3
        
    - name: jumphost login
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 1224 20.65.64.224 >> ~/.ssh/known_hosts
        az ssh vm --port 1224 -n numocity-jump-host -g numocity-jump-host_group "git clone https://${{ secrets.ORG_NPM_INSTALL }}@github.com/nischitha24/release_1.git"
        az ssh vm --port 1224 -n numocity-jump-host -g numocity-jump-host_group "bash release_1/makeCompose.sh ${{ secrets.ORG_NPM_INSTALL }} ${{ inputs.OrgRepo }} ${{ inputs.tag }} ${{ inputs.Host }}"
