name: jumphost_implementation
on: [push]
jobs:
  jumphost:
    runs-on: ubuntu-latest
    steps:
    - name: Install Azure CLI 
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Login to Azure
      run: az login
    - name: Set the default subscription
      run: az account set --subscription 92795555-74c0-409e-bf60-edb488699fb3
    - name: jumphost login
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        az ssh vm --port 1224 --name numocity-jump-host --resource-group numocity-jump-host_group
