name: condition_check
on:
   workflow_call:
   
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - run: echo "rachana"
      - name: Generate Variable
        id: generate_var
        run: |
          echo "::set-output name=my_var::Hello World"
      - name: Use Variable
        run: |
          echo "My variable is ${{ steps.generate_var.outputs.my_var }}"
