name: random
on:
  workflow_dispatch:
    
      
jobs:
  random:
    runs-on: ubuntu-latest
    steps:
      - name: random
        run: |
          ls -a
          openssl rand -base64 10 > random
          ls -a
          cat random
