name: test-ssh
on:
  workflow_dispatch:
    inputs:
      tag: 
        description: "Tag, e.g., SP.0.0.0"
        required: true
      OrgRepo:
        type: choice
        description: "org/repo, e.g., ncmsdev/ocpp-server"
        required: true
        options:
        - ncmsdev/ocpp-server
jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps: 
    - name: Login to Azure
      run: az login
    - name: Get public IP address
      id: public_ip
      run: |
        az network public-ip show \
        --resource-group numocity-jump-host_group \
        --name numocity-jump-host-ip \
        --query ipAddress \
        --output tsv
    - name : azure config
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        mkdir -p ~/.ssh
        ssh-keyscan -p 1224 20.65.64.224 >> ~/.ssh/known_hosts
    - name: checkout first server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 20.65.64.224
        username: nischitha.sj
        port: 1224
        script: |
          mkdir test
